language: python

python:
  - 3.5

cache: pip

install:
  - pip install -q -r requirements.txt
  - pip install -q pylint

script:
  - python3 -m pylint **/*.py --indent-string="  " --max-line-length=80 --disable=E1101,R0913,W0221,R0903,R0902,R0914,R0912,R0915
  - bash run_tests.sh
