language: python

python:
  - 3.5

cache: pip

install:
  - pip install -q -r requirements.txt

script:
  - python tests/evals_test.py
  - python tests/integration_test.py
  - python tests/uisrnn_test.py
  - python tests/utils_test.py