language: python

python:
  - 3.5

cache: pip

install:
  - pip install -q -r requirements.txt

script:
  - python -m unittest tests.evals_test
  - python -m unittest tests.integration_test
  - python -m unittest tests.uisrnn_test
  - python -m unittest tests.utils_test